# global.toml example
#
client_mode = "MONITOR"
#clean_sync = true
batch_size = 128
enable_bundles = false
enable_transitive_rules = true
full_sync_interval = 600
# allowed_path_regex = "^(?:/Users)/.*"
# blocked_path_regex = "^(?:/Users)/.*"
block_usb_mount = false
# remount_usb_mode = "rdonly"


# Example Rules:
# i chose Prime Video just because its not likely to break anyones workflow if you accidentally publish these rules in your own env
# unless of course you're the macadmin for amazon. in which case, sorry.
#

# [[rules]]
# rule_type = "BINARY"
# policy = "ALLOWLIST"
# sha256 = "264924e1f16c7051fe074e3d99ce1685d3ec9d82667ef469b632fc29141e33c6"
# custom_msg = "binary - Prime Video.app"

# [[rules]]
# rule_type = "CERTIFICATE"
# policy = "ALLOWLIST"
# sha256 = "ac7147809c6464989b0657ac0c646d8043280776fe588ba4bca71f1797003d57"
# custom_msg = "certificate - Amazon"

[[rules]]
rule_type = "TEAMID"
policy = "BLOCKLIST"
identifier = "94KV3E626L"
custom_msg = "teamid - Amazon Apps"
